---
title: "Lab One Reflection"
description: "Life After MicroPs Lab 1"
author: "Christian Johnson"
date: "9/2/25"
categories:
  - reflection
  - labreport
draft: false
---

Hi,

I just finished the proficiency specs for Lab 1. Overall, I feel good about the work I did, but there are definitely areas where I can improve. One of the biggest challenges I faced was getting the testbench working. I spent a lot of time debugging the Verilog code and my circuit itself, but in the end, I was able to get it working. If I was able to get my testbench working I would have been able to get all the specs on the lab and have an easier time with debugging.

Looking ahead, I want to focus on improving my debugging skills and becoming more comfortable with the tools we are using in this class. I also want to make sure I am keeping up with the checkpoints / specs for the lab, as I know that staying organized and on time is really important for this class.

Finally, I just wanted to note that I don't think I've ever spent this much time on one assignment at Harvey Mudd and I'm gonna need to ramp up quickly or figure something out.